# Generated by Django 5.1.3 on 2024-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0002_alter_exam_available_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='selected_time',
            field=models.CharField(max_length=5),
        ),
    ]
