# Generated by Django 5.1.2 on 2024-10-31 02:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0003_remove_exam_location_remove_exam_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='exam',
            name='sits_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cordialapp.location'),
        ),
    ]
