# Generated by Django 5.1.2 on 2024-10-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0004_location_exam_date_exam_sits_available_exam_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cordialapp.location'),
        ),
    ]
