# Generated by Django 5.1.3 on 2024-12-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0004_studentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'permissions': [('teacher_view', 'Can view registrations for reporting purposes')]},
        ),
    ]
