# Generated by Django 5.1.2 on 2024-11-07 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0005_alter_exam_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='gif_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='location',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sits_available',
        ),
        migrations.AddField(
            model_name='exam',
            name='available_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exam',
            name='locations',
            field=models.ManyToManyField(to='cordialapp.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Unknown Campus', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_exam_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField()),
                ('selected_time', models.TimeField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cordialapp.exam')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cordialapp.location')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'selected_date', 'selected_time')},
            },
        ),
    ]
