# Generated by Django 5.1.2 on 2024-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0006_remove_exam_gif_file_remove_exam_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(default='000', max_length=50),
        ),
    ]
