# Generated by Django 5.1.2 on 2024-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cordialapp', '0007_location_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='location',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
